### ISSUE TITLE
LF2, whaaaat?

### ISSUE THREAD

**Issue by mbomb007** [JohnDoeAntler/LF2-editor#1]
I happened to be searching for LineFeed-related extensions and noticed your two LF2 extensions for VS Code. I have played Little Fighter 2 and [Reinforced-LF2](https://www.lf-empire.de/lfe-fileplanet/versions/634-reinforced-little-fighter-2) a decent amount.

If I may ask, what work are you planning on doing with relation to the game(s)? It would be awesome if someone would fix the R-LF2 graphics issues on 64-bit machines due to the image-mirroring not working.

**Comment by JohnDoeAntler** [comment]
I am sorry that I know nothing about how the graphics rendering really works on this game thus I cannot fix the trouble you have got.

There is some related threads from LFE that might help you:
https://www.lf-empire.de/forum/showthread.php?tid=4442
https://www.lf-empire.de/forum/showthread.php?tid=6249

If you are looking for experts, join this server:
https://discord.gg/Z2MFSMD

**Comment by mbomb007** [comment]
So what are you planning to work on, then? Just curious.

**Comment by JohnDoeAntler** [comment]
I am planning to create an AI template (or an utils) for reducing the AI scripting difficulty, it will include commonly used functions such as:
1. trace object
2. dodge object
3. catch enemy
4. object in-range detection
5. diagonal object detection
6. map boundary detection, etc.
